services:
- type: web
  name: hasura-singapore-feb4-2
  env: docker
  region: singapore 
  autoDeploy: false
  healthCheckPath: /healthz
  envVars:
  - key: HASURA_GRAPHQL_METADATA_DATABASE_URL
    fromDatabase:
      name: hasura-metadata-singapore-feb4-2
      property: connectionString
  - key: HASURA_GRAPHQL_ENABLE_CONSOLE
    value: true
  - key: PORT
    value: 10000
  - key: HASURA_GRAPHQL_ADMIN_SECRET
    value: AGXDRJSMTjsy73UP7XaQviZtaryO6F20F7SYX5TQWTifAL39n3Qm9tonw2og7NS1
databases:
- name: hasura-metadata-singapore-feb4-2
  region: singapore
